### ISSUE TITLE
Option to generate black and white logo 

### ISSUE THREAD

**Issue by niyamax** [tinkerhub-org/campus-logo-generator#3]
The text color will change to white or black according to selection now

**Comment by monkeyscript** [comment]
@niyamax The text color should be black in the colored one. White won't make sense. What we can do is provide a full black copy and full white copy along with the colored one. That's better, right?

**Comment by niyamax** [comment]
No we don't use full black or white logo. Only text color needed to be changed. It's basically to use in dark and white background accordingly. @monkeyscript
